# permissions to do viewer redis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-viewer-role
rules:
- apiGroups:
  - webapp.kops.ust-global-lab.com
  resources:
  - redis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.kops.ust-global-lab.com
  resources:
  - redis/status
  verbs:
  - get
